/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ru4ly5tZ3xo
 */
import { CardTitle, CardDescription, CardHeader, CardFooter, Card } from "@/components/ui/card"
import Link from "next/link"

export function test() {
  return (
    <div>
      <div className="space-y-6">
        <div className="space-y-2">
          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <img
                alt="Avatar"
                className="rounded-full"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
              <div className="space-y-1.5">
                <h1 className="text-2xl font-bold tracking-tighter">Dr. Maria Garcia</h1>
                <p className="text-sm text-gray-500 leading-none dark:text-gray-400">@mariagarcia</p>
              </div>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 items-start gap-4">
            <div className="space-y-4">
              <section>
                <h2 className="text-lg font-semibold">Bio</h2>
                <p className="text-sm text-gray-500 leading-none dark:text-gray-400">
                  Family physician with a passion for patient care and community health. Dedicated to continuous
                  learning and improvement in medical practice.
                </p>
              </section>
              <section>
                <h2 className="text-lg font-semibold">Specialties</h2>
                <ul className="grid grid-cols-1 gap-2 list-disc list-inside text-sm">
                  <li>Family Medicine</li>
                  <li>Preventive Care</li>
                  <li>Chronic Disease Management</li>
                </ul>
              </section>
            </div>
            <div className="space-y-4">
              <section>
                <h2 className="text-lg font-semibold">Qualifications</h2>
                <ul className="grid grid-cols-1 gap-2 list-disc list-inside text-sm">
                  <li>MD, Universidad Autónoma de Madrid</li>
                  <li>Residency in Family Medicine, Hospital Clínico San Carlos</li>
                  <li>Board Certified in Family Medicine</li>
                </ul>
              </section>
            </div>
          </div>
        </div>
        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Community Health Fair</CardTitle>
              <CardDescription>Organizing a health fair to promote wellness in the neighborhood</CardDescription>
            </CardHeader>
            <CardFooter>
              <Link className="font-semibold underline" href="#">
                View Details
              </Link>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Research Project</CardTitle>
              <CardDescription>Investigating the impact of social support on patient outcomes</CardDescription>
            </CardHeader>
            <CardFooter>
              <Link className="font-semibold underline" href="#">
                View Details
              </Link>
            </CardFooter>
          </Card>
        </div>
        <div className="space-y-2">
          <h2 className="text-2xl font-bold">Contact</h2>
          <div className="grid gap-1.5">
            <p className="text-base">Email: contact@mariagarciamd.com</p>
            <p className="text-base">Phone: +1 (123) 456-7890</p>
          </div>
        </div>
        <div className="space-y-2">
          <h2 className="text-2xl font-bold">Social</h2>
          <div className="grid gap-1.5">
            <p className="text-base">Twitter: @mariagarciamd</p>
            <p className="text-base">LinkedIn: /in/mariagarciamd</p>
          </div>
        </div>
      </div>
    </div>
  )
}
